#!/bin/bash

cmake -D 3RD_PARTY_INSTALL_STEP=True -D PRE_COMPILE_STEP=False -D COMPILATION_STEP=False . && make
cmake -D COMPILATION_STEP=False -D PRE_COMPILE_STEP=True -D 3RD_PARTY_INSTALL_STEP=False . && make
cmake -D COMPILATION_STEP=True -D PRE_COMPILE_STEP=False -D 3RD_PARTY_INSTALL_STEP=False . && make
