find_path(CORE_INCLUDE_DIR NAMES core/Exception.h PATHS ${PROJECT_3RD_LOC}/include NO_DEFAULT_PATH)
find_program(CORE_LIBRARY_DIR NAMES libCore.so PATHS ${PROJECT_3RD_LOC}/lib NO_DEFAULT_PATH)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Core REQUIRED_VARS CORE_INCLUDE_DIR)

if(Core_FOUND)
    message(STATUS ${Green}"Found Core include dir - ${CORE_INCLUDE_DIR}"${ColourReset})
    message(STATUS ${Green}"Found Core library dir - ${CORE_LIBRARY_DIR}"${ColourReset})
else()
    message(WARNING ${Red}"Core not found"${ColourReset})
endif()
