find_path(POCO_INCLUDE_DIR NAMES Poco/JSON/JSON.h PATHS ${PROJECT_3RD_LOC}/include)
if(WIN32)
	find_program(POCO_LIBRARY_DIR NAMES PocoJSON.dll PATHS ${PROJECT_3RD_LOC}/lib)
else()
	find_program(POCO_LIBRARY_DIR NAMES libPocoJSON${POCO_SUFFIX}.so PATHS ${PROJECT_3RD_LOC}/lib)
endif()	
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(POCO REQUIRED_VARS POCO_INCLUDE_DIR POCO_LIBRARY_DIR)

if(POCO_FOUND)
    message(STATUS "Found POCO include dir - ${Green}${POCO_INCLUDE_DIR}${ColourReset}")
    message(STATUS "Found POCO library dir - ${Green}${POCO_LIBRARY_DIR}${ColourReset}")
else()
    message(WARNING ${Red}"POCO not found"${ColourReset})
endif()
